galaxy_info:
  role_name: notes_app
  author: marwasad
  description: Deploy Flask Notes App with SQLite, backups, nginx, and systemd
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - 8
        - 9

  galaxy_tags:
    - flask
    - sqlite
    - nginx
    - backup
    - systemd

dependencies: []
